### ISSUE TITLE
Try but doesn't seems to extract anything

### ISSUE THREAD

**Issue by BlueWaver** [Jayveer/Solideye#3]
Hi I try your program but the only thing it said is this 

"Running Solideye v1.1: Visit https://github.com/Jayveer/Solideye for updates:"

and I download the directory and put it in same directory as the file
my command line is this 

Solideye.exe "stage00.dat"

or this

Solideye.exe "D:\DW\Metal gear 4\NPUB31633\USRDIR\mgs\stage01.dat"

is there something wrong with my line ?

**Comment by BlueWaver** [comment]
Becarefull of corrupt file

**Comment by quarth4583** [comment]
hey u closed the issue, DID YOU FIGURE IT OUT??? im struggling with the same thing.
